### Numpy Assignment

1.  Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.<br>


SOL:  https://www.w3resource.com/python-exercises/numpy/basic/numpy-basic-exercise-13.php


In [2]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)
array=np.ones(10)
print("An array of 10 ones:")
print(array)
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


2.  Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21. <br>
SOL: https://www.w3resource.com/python-exercises/numpy/basic/numpy-basic-exercise-25.php

In [3]:
import numpy as np
m= np.arange(10,22).reshape((3, 4))
print(m)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


3.  Write a NumPy program to check whether two arrays are equal (element wise) or not.<br>

SOL: https://www.w3resource.com/python-exercises/numpy/basic/numpy-basic-exercise-44.php

In [4]:
import numpy as np
nums1 = np.array([0.5, 1.5, 0.2])
nums2 = np.array([0.4999999999, 1.500000000, 0.2])
np.set_printoptions(precision=15)
print("Original arrays:")
print(nums1)
print(nums2)
print("\nTest said two arrays are equal (element wise) or not:?")
print(nums1 == nums2)
nums1 = np.array([0.5, 1.5, 0.23])
nums2 = np.array([0.4999999999, 1.5000000001, 0.23])
print("\nOriginal arrays:")
np.set_printoptions(precision=15)
print(nums1)
print(nums2)
print("\nTest said two arrays are equal (element wise) or not:?")
print(np.equal(nums1, nums2))

Original arrays:
[0.5 1.5 0.2]
[0.4999999999 1.5          0.2         ]

Test said two arrays are equal (element wise) or not:?
[False  True  True]

Original arrays:
[0.5  1.5  0.23]
[0.4999999999 1.5000000001 0.23        ]

Test said two arrays are equal (element wise) or not:?
[False False  True]


4.  Write a NumPy program to swap rows and columns of a given array in reverse order. <br>

SOL: https://www.w3resource.com/python-exercises/numpy/basic/numpy-basic-exercise-58.php

In [5]:
import numpy as np
nums = np.array([[[1, 2, 3, 4],
               [0, 1, 3, 4],
               [90, 91, 93, 94],
               [5, 0, 3, 2]]])
print("Original array:")
print(nums)
print("\nSwap rows and columns of the said array in reverse order:")
new_nums = print(nums[::-1, ::-1])
print(new_nums)


Original array:
[[[ 1  2  3  4]
  [ 0  1  3  4]
  [90 91 93 94]
  [ 5  0  3  2]]]

Swap rows and columns of the said array in reverse order:
[[[ 5  0  3  2]
  [90 91 93 94]
  [ 0  1  3  4]
  [ 1  2  3  4]]]
None


5. Write a NumPy program to create a null vector of size 10 and update sixth value to 11.<br>
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]<br>
Update sixth value to 11<br>
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]<br>

SOL: https://www.w3resource.com/python-exercises/numpy/python-numpy-exercise-4.php

In [7]:
import numpy as np
x = np.zeros(10)
print(x)
print("Update sixth value to 11")
x[6] = 11
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


6. Write a NumPy program to convert a list and tuple into arrays. <br>
List to array:<br>
[1 2 3 4 5 6 7 8]<br>
Tuple to array:<br>
[[8 4 6]<br>
[1 2 3]]<br>

SOL: https://www.w3resource.com/python-exercises/numpy/python-numpy-exercise-11.php

In [8]:
import numpy as np
my_list = [1, 2, 3, 4, 5, 6, 7, 8]
print("List to array: ")
print(np.asarray(my_list))
my_tuple = ([8, 4, 6], [1, 2, 3])
print("Tuple to array: ")
print(np.asarray(my_tuple))

List to array: 
[1 2 3 4 5 6 7 8]
Tuple to array: 
[[8 4 6]
 [1 2 3]]


7.  Write a NumPy program to change the dimension of an array. <br>
Expected Output:<br>
6 rows and 0 columns<br>
(6,)<br>
(3, 3) -> 3 rows and 3 columns<br>
[[1 2 3]<br>
[4 5 6]<br>
[7 8 9]]<br>
Change array shape to (3, 3) -> 3 rows and 3 columns<br>
[[1 2 3]<br>
[4 5 6]<br>
[7 8 9]]<br>

SOL: https://www.w3resource.com/python-exercises/numpy/python-numpy-exercise-35.php

In [9]:
import numpy as np
x = np.array([1, 2, 3, 4, 5, 6])
print("6 rows and 0 columns")
print(x.shape)

y = np.array([[1, 2, 3],[4, 5, 6],[7,8,9]])
print("(3, 3) -> 3 rows and 3 columns ")
print(y)

x = np.array([1,2,3,4,5,6,7,8,9])
print("Change array shape to (3, 3) -> 3 rows and 3 columns ")
x.shape = (3, 3)
print(x)

6 rows and 0 columns
(6,)
(3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Change array shape to (3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


8. Write a NumPy program to compute the multiplication of two given matrices.<br>
SOL: https://www.w3resource.com/python-exercises/numpy/linear-algebra/numpy-linear-algebra-exercise-1.php

In [11]:
import numpy as np
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print("original matrix:")
print(p)
print(q)
result1 = np.dot(p, q)
print("Result of the said matrix multiplication:")
print(result1)

original matrix:
[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
Result of the said matrix multiplication:
[[1 2]
 [3 4]]


9. Write a NumPy program to create a 3x3x3 array with random values. <br>
Expected Output: <br>
[[[ 0.48941799 0.58722213 0.43453926] <br>
[ 0.94497547 0.81081709 0.1510409 ] <br>
[ 0.66657127 0.29494755 0.48047144]] <br>
[[ 0.02287253 0.95232614 0.32264936] <br>
[ 0.67009741 0.25458304 0.16290913] <br>
[ 0.15520198 0.86826529 0.9679322 ]]  <br>
[[ 0.13503103 0.02042211 0.24683897]  <br>
[ 0.97852158 0.22374748 0.10798856]  <br>
[ 0.62032646 0.5893892 0.16958144]]] <br>

SOL: https://www.w3resource.com/python-exercises/numpy/python-numpy-random-exercise-3.php

In [12]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.36847996276071  0.629224331537572 0.353356270214546]
  [0.14458618153372  0.101536509812987 0.683098621036229]
  [0.042552994610491 0.213001560233704 0.896152099778048]]

 [[0.484729356098737 0.818203483366454 0.889096908285991]
  [0.267203671017091 0.401255626883542 0.352595905035282]
  [0.577825545408861 0.389832222590296 0.790907678623961]]

 [[0.279830054283708 0.834141876169246 0.11942535138391 ]
  [0.647436675082134 0.684968132276115 0.255804082139794]
  [0.336116707679677 0.814425678560646 0.285017468602564]]]


10. Write a NumPy program to sort the student id with increasing height of the students from given students id and height. Print the integer indices that describes the sort order by multiple columns and the sorted data. <br>
Expected Output: <br>
Sorted indices: <br>
[4 0 5 3 6 1 2] <br>
Sorted data:  <br>
1682 38.0  <br>
1023 40.0  <br>
5241 40.0  <br>
1671 41.0  <br>
4532 42.0  <br>
5202 42.0  <br>
6230 45.0  <br>

SOL: https://www.w3resource.com/python-exercises/numpy/python-numpy-sorting-and-searching-exercise-4.php

In [13]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
student_height = np.array([40., 42., 45., 41., 38., 40., 42.0])
#Sort by studen_id then by student_height
indices = np.lexsort((student_id, student_height))
print("Sorted indices:")
print(indices)
print("Sorted data:")
for n in indices:
  print(student_id[n], student_height[n])

Sorted indices:
[4 0 5 3 6 1 2]
Sorted data:
1682 38.0
1023 40.0
5241 40.0
1671 41.0
4532 42.0
5202 42.0
6230 45.0
